---
- name: Converge
  hosts: all
  vars:
    wildfly_home: '/opt/wildfly/wildfly-27.0.0.Final'
    wildfly_java_home: '/usr/lib/jvm/jre-openjdk/'
    wildfly_java_package_name: java-11-openjdk-headless
    wildfly_user: 'wildfly'
    wildfly_group: "{{ wildfly_user }}"
  collections:
    - middleware_automation.wildfly
  roles:
    - wildfly_install
    - wildfly_systemd

  tasks:
    - meta: flush_handlers

  post_tasks:
    - name: "Run Common Criteria role on setup"
      ansible.builtin.include_role:
        name: ../../roles/wildfly_common_criteria
