---
- name: Check that required parameters are provided
  assert:
    that:
      - jbossas_interface is defined
    fail_msg: "Required parameter 'jbossas_interface' not provided"
    quiet: true

- set_fact:
    interface_name: "{{ jbossas_interface.address[0].interface }}"

- block:
    - set_fact:
        fail_msg:
          - "{{ interface_name }} is not a Common Criteria compliant name for an inteface"

    - name: Check that interface {{ interface_name }} is a name in compliance with Common Criteria recommendations
      assert:
        that:
          - interface_name in allowed_network_interfaces
        fail_msg: "{{ fail_msg[0] }}"
        quiet: true
  rescue:
    - set_fact:
        compliance_violations: "{{ (compliance_violations | int) + 1 }}"
        compliance_issues: "{{ compliance_issues + fail_msg }}"
