---
jws_common_criteria:
  display_xpath_res: "{{ display_xpath_res_override | default('False') }}"
display_directory_stats: "{{ display_directory_stats_override | default('true') }}"
jws_user: "{{ jws_owner_override | default('tomcat') }}"
jws_group: "{{ jws_group_override | default('tomcat') }}"
